#pragma once
#include <QEventLoop>
#include <QGridLayout>
#include <QMainWindow>
#include <QScrollArea>
#include <optional>
#include "i_input_output.hpp"


// forward declaration of ui class
// this class will be autogenerated from .ui file
// (see https://doc.qt.io/qt-5/qtwidgets-tutorials-notepad-example.html for more information)
QT_BEGIN_NAMESPACE
namespace Ui {
class MainWindow;
}
QT_END_NAMESPACE


class GUI_InputOutput final : public QMainWindow
    , public I_InputOutput
{
    Q_OBJECT

public:
    GUI_InputOutput();
    virtual ~GUI_InputOutput();

    FieldSize readFieldSize() override;
    void initField(std::shared_ptr<Field> field) override;
    void updateField(std::shared_ptr<Field> field) override;

    PlayerType getPlayerType(std::string_view msg) override;
    uint32_t getMarksInRowToWinCount(uint32_t maxValue) override;
    CellPosition readPlayerInput() override;
    void showMessage(std::string_view msg) override;

private:
    Ui::MainWindow* ui;

    QEventLoop inputLoop;
    std::optional<CellPosition> userInput_;

    QScrollArea* scrollArea;
    QWidget* fieldWidget;
    QGridLayout* gridLayout;
};
