#include "input_output.h"
#include <QInputDialog>
#include <QMessageBox>
#include <QPushButton>
#include <field.h>
#include "ui_mainwindow.h" // autogenerated by QT


GUI_InputOutput::GUI_InputOutput()
    : QMainWindow(nullptr)
    , ui(new Ui::MainWindow())
    , scrollArea(new QScrollArea(this))
    , fieldWidget(new QWidget)
{
    ui->setupUi(this);
    setCentralWidget(scrollArea);
    show();
}

GUI_InputOutput::~GUI_InputOutput()
{
    delete ui;
}

FieldSize GUI_InputOutput::readFieldSize()
{
    QString windowTitle = "Input field size";
    QString inputTitle = "Field size(N*N):";
    int defaultValue = 3;
    int minValue = 1;
    int maxValue = 1000;
    int step = 1;
    bool ok = false;

    int size = defaultValue;
    while(!ok) {
        size = QInputDialog::getInt(this, windowTitle,
                                    inputTitle, defaultValue, minValue, maxValue, step, &ok);
    }
    return {size, size};
}

void GUI_InputOutput::initField(std::shared_ptr<Field> field)
{
    auto size = field->getSize();
    gridLayout = new QGridLayout();
    for(uint32_t row = 0; row < size.getRowsCount(); ++row) {
        for(uint32_t column = 0; column < size.getColumnsCount(); ++column) {
            auto button = new QPushButton("");
            auto handleClick = [this, row, column] {
                auto button = qobject_cast<QPushButton*>(sender());
                if(!button->text().isEmpty()) {
                    showMessage("Field already marked! Select another field");
                } else {
                    userInput_ = {row, column};
                    inputLoop.quit();
                }
            };
            connect(button, &QPushButton::released, this, handleClick);
            gridLayout->addWidget(button, row, column);
        }
    }

    fieldWidget->setLayout(gridLayout);
    scrollArea->setWidget(fieldWidget);
}

void GUI_InputOutput::updateField(std::shared_ptr<Field> field)
{
    auto size = field->getSize();
    for(uint32_t row = 0; row < size.getRowsCount(); ++row) {
        for(uint32_t column = 0; column < size.getColumnsCount(); ++column) {
            auto button = qobject_cast<QPushButton*>(gridLayout->itemAtPosition(row, column)->widget());
            QString newText = "";
            auto cellstate = field->getCellState({row, column});
            if(cellstate.has_value()) {
                newText = cellstate.value() == MarkType::x ? "X" : "O";
            }
            button->setText(newText);
        }
    }
}

CellPosition GUI_InputOutput::readPlayerInput()
{
    userInput_ = std::nullopt;
    inputLoop.exec();
    return userInput_.value();
}

void GUI_InputOutput::showMessage(std::string_view msg)
{
    QMessageBox msgBox;
    msgBox.setText(msg.data());
    msgBox.exec();
}
