#pragma once
#include <QGridLayout>
#include <QMainWindow>

// forward declaration of ui class
// this class will be autogenerated from .ui file
// (see https://doc.qt.io/qt-5/qtwidgets-tutorials-notepad-example.html for more information)
QT_BEGIN_NAMESPACE
namespace Ui {
class MainWindow;
}
QT_END_NAMESPACE


class MainWindow : private QMainWindow
{
    Q_OBJECT

public:
    MainWindow(QWidget* parent = nullptr);
    void renderField();
    ~MainWindow();

private slots:
    void onClicked();

private:
    std::unique_ptr<Ui::MainWindow> ui;
    QGridLayout* layout = new QGridLayout;
};
